services:
  postgres:
    image: postgres:14-alpine
    container_name: salary_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: salary_calculator
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # ↓↓↓ NUEVO SERVICIO PARA NUESTRA API ↓↓↓
  api:
    # Usa la imagen que construimos en el paso anterior
    image: calculadora-sueldo-api
    container_name: mi-api
    # Indicamos que este servicio depende de la base de datos.
    # Docker Compose esperará a que postgres esté listo para iniciar la api.
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    # Pasamos las variables de entorno aquí
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    restart: unless-stopped
volumes:
  postgres_data: